### ISSUE TITLE
Feature Request: Select current entry

### ISSUE THREAD

**Issue by richhayler** [Dolphiq/craft3-plugin-link-to-field#3]
Please can you incorporate the abiliy to select the current entry from the list of entries. I’m using the plugin to create a sub menu for pages within a structure and this is the one feature that is missing for me. Thank you.

**Comment by johanzandstra** [comment]
@richhayler  would you like to create some kind of a tree structure?

**Comment by richhayler** [comment]
I’m creating a nav for nested entries within a structure section. I don’t want all nested pages to be included in the navigation and I want the nav items to display the same across all the pages. Using your plugin allows me to create the custom nav on each entry for the set of pages I want. Having the ability to select the current entry means the nav appears the same across all those pages.

**Comment by johanzandstra** [comment]
Can you use a matrix field for this? With the title entries field in the block type, like I use in the screenshot in the [readme](https://github.com/Dolphiq/craft3-plugin-title-entries-field/blob/master/README.md) ?

**Comment by richhayler** [comment]
Thanks @johanzandstra I can give that a try but I still think my request has merit. Just seems simpler to add the entries rather than having to add these within a matrix. In my case the sub nav could just be a handful of links (3-4) so it seems a little overkill to use a matrix.

**Comment by dolphiq-allard** [comment]
Hey Guys,

To get things straight: am I correct to asume that all you want is the current entry to show up in the list so you can select it and have identical lists in all entries where needed.

How it currently works:
Say I am editing "Entry 3", I am unable to select this option, so my list would look like:

- Entry 1
- Entry 2
- Entry 4
- Entry 5

What you would like to see:
Entry 3 should be selectable from within Entry 3 so the list could look like:
- Entry 1
- Entry 2
- Entry 3
- Entry 4
- Entry 5

Is this what you mean?

**Comment by richhayler** [comment]
Exactly! :)

**Comment by dolphiq-allard** [comment]
Alright!! We're on the same page then ;-)

We will look into this one and keep you posted.

Thanks for your feedback!!

**Comment by richhayler** [comment]
Thank you @johanzandstra and sorry for not doing a great job explaining what I was after. Really appreciate your plugin and considering my request. Thanks 👍

**Comment by johanzandstra** [comment]
Just released the described additions #5  ! Please let us know if this works for you, thanks!

**Comment by dolphiq-allard** [comment]
Thanks all, closing this issue...

**Comment by richhayler** [comment]
Thanks for turning this around so quickly!! I've just updated via the CP to v1.04 but unfortunately its not working for me. The current entry is still disabled in the structure tree.

**Comment by richhayler** [comment]
I'm also running Craft Pro 3.0.0-RC2

**Comment by johanzandstra** [comment]
Strange, It's working for me, have you tried to clear the (browser) cache? The .js file could be cached

**Comment by johanzandstra** [comment]
![screen shot 2017-12-13 at 17 05 51](https://user-images.githubusercontent.com/4737521/33948758-07288f0e-e028-11e7-9a87-a3a1c38c552e.png)

**Comment by richhayler** [comment]
That did it! Thank you for making this change.

**Comment by johanzandstra** [comment]
Thanks for the feedback!
