### ISSUE TITLE
Problems with PHP 7.2

### ISSUE THREAD

**Issue by mikestecker** [Dolphiq/craft3-plugin-link-to-field#7]
I was just testing out this [cool script](https://github.com/jalendport/switch-php) that allows you to switch php versions on the fly and when I switched to 7.2 I noticed this error when loading Craft and it seemed to come from this plugin:

```
Cannot use craft\base\Object as Object because 'Object' is a special class name
in [removed for brevity]/vendor/dolphiq/titleentriesfield/src/TitleEntriesFieldPlugin.php at line 24

...

24  use craft\base\Object;

```

**Comment by johanzandstra** [comment]
@mikestecker thanks for your feedback, we have released an update for this.  Can you please let us know if the update fix this issue, thanks!

**Comment by mikestecker** [comment]
Sorry for the late reply... seems to have fixed it! Thanks!
